##############################################
# Main task that executes this ansible role  
##############################################

- name: verify hosts is available
  include_tasks: "00.ping_test.yml"
  
- name: Verify requiremnts is done 
  include_tasks: "01.requirements.yml"
  
##############################################
# Start containers 
##############################################

- name: Start MySQL Master
  include_tasks: "nodes/node1.yml"
  
- name: Start MySQL Slave
  include_tasks: "nodes/node2.yml"
  
  

