---
- name: DevOps Test Redis Cluster
  hosts: redisms1
  serial: 1
  gather_facts: false
  become: yes
  roles:
    - redis-docker-deploy

# - name: RabbitMQ cluster
#   hosts: rabbitmq-server
  
#   roles:
#     - rabbitmq-server-deploy

# - name: MySQL cluster 
#   hosts: mysql-server
#   roles:
#     - mysql-server-deploy
    
 