---

  
#  __   __  _____              ____              _______        _   
#  \ \ / / |  __ \            / __ \            |__   __|      | |  
#   \ V /  | |  | | _____   _| |  | |_ __  ___     | | ___  ___| |_ 
#    > <   | |  | |/ _ \ \ / / |  | | '_ \/ __|    | |/ _ \/ __| __|
#   / . \  | |__| |  __/\ V /| |__| | |_) \__ \    | |  __/\__ \ |_ 
#  /_/ \_\ |_____/ \___| \_/  \____/| .__/|___/    |_|\___||___/\__|
#                                   | |                             
#                                   |_|                             

##########################
# Ansible Playbook
#########################

- name: DevOps Test Redis Cluster
  hosts: rediscluster
  serial: 1
  gather_facts: false
  become: yes
  roles:
    - redis-docker-deploy
  tags: redis  

- name: RabbitMQ cluster
  hosts: rabbitmqcluster
  roles:
    - rabbitmq-docker-deploy
  tags: rabbitmq  

- name: MySQL cluster 
  hosts: mysqlcluster
  become: yes
  roles:
    - mysql-docker-deploy
  tags: mysql  
    
 