---
- name: DevOps Test Redis Cluster
  hosts: rediscluster
  serial: 1
  gather_facts: false
  become: yes
  roles:
    - redis-docker-deploy
  tags: redis  

- name: RabbitMQ cluster
  hosts: rabbitmqcluster
  roles:
    - rabbitmq-docker-deploy
  tags: rabbitmq  

- name: MySQL cluster 
  hosts: mysqlcluster
  roles:
    - mysql-docker-deploy
  tags: mysql  
    
 