###############################################
# MASTER1 VARIABLES FOR THE REDIS CLUSTER
###############################################
node_port: 7006
app_name: "redis_node6"
container_name: "{{ app_name }}"
docker_image_name: redis
docker_image_version: "5"
# docker_network_name: "{{ app_name }}_network"
# docker_network_mode: "host"
docker_container_name: "{{ app_name }}"
# docker_command: "redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 --cluster-replicas 1"
docker_container_mapped_port:
  - 6379
  - 16379

