---

- name: Update the repository cache
  apt:
    update_cache: yes

- name: Install prerequisite packages (state=present is optional)
  apt:
    name: 
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# - name: Add Docker's official GPG key 
#   shell: "curl -y -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

- name: Setup repository
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

###################################
# Install Docker
###################################

- name: Checking the installation of the docker package
  shell: "dpkg -l | grep docker.*"
  register: package_docker

- name: Update the repository cache
  apt:
    update_cache: yes
  when: package_docker.rc == 1   

- name: Install Docker  (state=present is optional)
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: package_docker.rc == 1

- name: Add the user 'vagrant' to the group 'docker'
  user:
    name: vagrant
    comment: Vagrant
    groups: docker,sudo
    append: yes
# - name: check if docker is installed
  
# - name: Install docker
#   pip:
#     name: docker

- name: Checking the installation of the docker package
  shell: "dpkg -l | grep docker.*"
  register: package_docker
  failed_when: package_docker.rc == 1

- name: Create a redis network
  docker_network:
    name: redis_network       


