---

# - name: Create Redis Cluster
#   shell: "docker exec -it redis-cli --cluster create redis_node1:7001 redis_node2:7002 redis_node3:7003 redis_node4:7004 redis_node:7005 redis_node6:7006 --cluster-replicas 1"
#   register: cluster_info

# - name: Create cluster
#   debug:
#     var: cluster_info

- name: check if Redis cluster is up
  shell: "docker exec -it redis_node1 redis-cli -h redis_node1 cluster info"
  register: result

- name: Run cluster creation script
  expect:
    command: "docker run -it --network redis_network --rm redis:5 redis-cli --cluster create 172.20.0.2:6379 172.20.0.3:6379 172.20.0.4:6379 172.20.0.5:6379 172.20.0.6:6379 172.20.0.7:6379 --cluster-replicas 1"
    responses:
      Question:
        - yes
  # ignore_errors: yes
  when: result is failed      