---
###################################
# Check install docker deployments #
###################################

# show container with restarting mode
- name: Verify if containers is up {{ docker_container_name }}
  shell: "docker ps -aq --filter name={{ docker_container_name }} --filter status=restarting --filter status=exited --latest | wc -l"
  register: container_run_count

# Check if docker deployment is OK
- name: "Check if docker deployment is OK"
  debug:
    msg: "Container {{ docker_container_name }} is OK"
  when:  container_run_count.stdout == "0"  

# Check if docker deployment is KO
- name: Check if docker deployment is KO
  fail: 
    msg: "Container {{ docker_container_name }} is KO"
  when: container_run_count.stdout == "1"
 
