##############################################
# Main task that executes this ansible role  
##############################################

- name: verify hosts is available
  include_tasks: "00.ping_test.yml"

- name: verify variables set 
  include_tasks: "01.check_variables.yml"
  
- name: Verify requiremnts is done 
  include_tasks: "02.requirements.yml"
  when: docker_action_require == true

- name: Deploy and start the containers with new version
  include_tasks: "04.deploy.yml"
  when: docker_action_deploy == true 

- name: Check deployment status
  include_tasks: "06.check_install.yml"
  when: docker_action_check == true   
