##############################################
# Main task that executes this ansible role  
##############################################

- name: verify hosts is available
  include_tasks: "00.ping_test.yml"
  
- name: Verify requiremnts is done 
  include_tasks: "01.requirements.yml"
  
##############################################
# Start containers 
##############################################

- name: Start Redis Node1
  include_tasks: "nodes/node1.yml"
  
- name: Start Redis Node2
  include_tasks: "nodes/node2.yml"
  
- name: Start Redis Node3
  include_tasks: "nodes/node3.yml"
  
- name: Start Redis Node4
  include_tasks: "nodes/node4.yml"
  
- name: Start Redis Node5
  include_tasks: "nodes/node5.yml"

- name: Start Redis Node6
  include_tasks: "nodes/node6.yml"

##############################################
# Start cluster
##############################################

- name: Start Redis Cluster
  include_tasks: "03_create_cluster.yml"     
