##############################################
# Main task that executes this ansible role  
##############################################

- name: verify hosts is available
  include_tasks: "00.ping_test.yml"
  
- name: Verify requiremnts is done 
  include_tasks: "01.requirements.yml"
  
##############################################
# Start containers 
##############################################

- name: Start Redis Master1
  include_tasks: "nodes/redisms1.yml"
  
- name: Start Redis Master2
  include_tasks: "nodes/redisms2.yml"
  
- name: Start Redis Master3
  include_tasks: "nodes/redisms3.yml"
  
- name: Start Redis Slave1
  include_tasks: "nodes/rediss1.yml"
  
- name: Start Redis Slave2
  include_tasks: "nodes/rediss2.yml"

- name: Start Redis Slave3
  include_tasks: "nodes/rediss3.yml"

##############################################
# Start cluster
##############################################

- name: Start Redis Cluster
  include_tasks: "03_create_cluster.yml"     
