---

- name: Stop all containers of the same name rabbit3@testvm
  docker_container:
    state: absent
    name: "rabbitmq3"

- name: Create a directory if it does not exist
  file:
    path: /vagrant/rabbitmq/conf
    state: directory
    mode: '0755'

- name: Start the container rabbitmq3
  docker_container:
    state: started
    name: "rabbitmq3"
    image: "rabbitmq:3"
    env: 
      RABBITMQ_ERLANG_COOKIE: 'UoNOcDhfxW9uoZ92wh6BjA=='
    hostname: testvm
    network_mode: host
    volumes:
      - /vagrant/rabbitmq/conf:/var/lib/rabbitmq
    container_default_behavior: no_defaults
    
###################################
# Check install docker deployments #
###################################

# show container with restarting mode
- name: Verify if containers is up rabbit3@testvm
  shell: "docker ps -aq --filter name=rabbitmq3 --filter status=restarting --filter status=exited --latest | wc -l"
  register: container_run_count

# Check if docker deployment is OK
- name: "Check if docker deployment is OK"
  debug:
    msg: "Container rabbit3@testvm is OK"
  when:  container_run_count.stdout == "0"  

# Check if docker deployment is KO
- name: Check if docker deployment is KO
  fail: 
    msg: "Container rabbitmq3 is KO"
  when: container_run_count.stdout == "1"
 
 