---

- name: Stop all containers of the same name mysql_slave
  docker_container:
    state: absent
    name: "rabbitmq2"

- name: Create a directory if it does not exist
  file:
    path: /vagrant/rabbitmq/conf
    state: directory
    mode: '0755'

- name: Start the container rabbit2@testvm
  docker_container:
    state: started
    name: "mysql_slave"
    image: "mysql:5.7"
    restart: "no"
    ports:
      - 5506:3306
    # depends_on:
    #   - mysql_master
    volumes:
      - ./slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./slave/data:/var/lib/mysql
    networks:
      - overlay
    
    
###################################
# Check install docker deployments #
###################################

# show container with restarting mode
- name: Verify if containers is up mysql_slave
  shell: "docker ps -aq --filter name=mysql_slave --filter status=restarting --filter status=exited --latest | wc -l"
  register: container_run_count

# Check if docker deployment is OK
- name: "Check if docker deployment is OK"
  debug:
    msg: "Container mysql_slave is OK"
  when:  container_run_count.stdout == "0"  

# Check if docker deployment is KO
- name: Check if docker deployment is KO
  fail: 
    msg: "Container mysql_slave is KO"
  when: container_run_count.stdout == "1"
 

    