---

- name: Stop all containers of the same name ndb3
  docker_container:
    state: absent
    name: "ndb3"

- name: Create a directory if it does not exist
  file:
    path: /vagrant/rabbitmq/conf
    state: directory
    mode: '0755'

- name: Start the container MySQL Node3
  docker_container:
    state: started
    name: "ndb3"
    image: "mysql/mysql-cluster"
    networks_cli_compatible: yes
    network_mode: mysql_cluster_network
    volumes:
      - /vagrant/mysql/node2/data:/data
    command: "ndbd"
    container_default_behavior: no_defaults
    
###################################
# Check install docker deployments #
###################################

# show container with restarting mode
- name: Verify if containers is up ndb3
  shell: "docker ps -aq --filter name=ndb3 --filter status=restarting --filter status=exited --latest | wc -l"
  register: container_run_count

# Check if docker deployment is OK
- name: "Check if docker deployment is OK"
  debug:
    msg: "Container ndb3 is OK"
  when:  container_run_count.stdout == "0"  

# Check if docker deployment is KO
- name: Check if docker deployment is KO
  fail: 
    msg: "Container ndb3 is KO"
  when: container_run_count.stdout == "1"
 
 